// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAllPerson():Promise<Array<main.PersonId>>;

export function GetPersonByID(arg1:string):Promise<main.PersonWithDetails>;

export function GetPersonByIdAndFio(arg1:string):Promise<main.PersonId>;

export function GetPersonList(arg1:string):Promise<main.SearchResult>;

export function Greet(arg1:string):Promise<string>;

export function LoadFromJSON():Promise<Array<main.Person>>;

export function SaveToJSON(arg1:string,arg2:Array<main.Person>):Promise<void>;

export function SaveUsersToJSONFile(arg1:Array<main.Person>):Promise<Array<main.Person>>;

export function UpdatePersonByID(arg1:string,arg2:main.Person,arg3:Array<main.Person>):Promise<string>;
