// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAllPerson():Promise<Array<main.PersonId>>;

export function Greet(arg1:string):Promise<string>;

export function LoadFromJSON():Promise<Array<main.Person>>;

export function SaveToJSON(arg1:string,arg2:Array<main.Person>):Promise<void>;

export function SaveUsersToJSONFile(arg1:Array<main.Person>):Promise<Array<main.Person>>;
