// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllPerson() {
  return window['go']['main']['App']['GetAllPerson']();
}

export function GetPersonList(arg1) {
  return window['go']['main']['App']['GetPersonList'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadFromJSON() {
  return window['go']['main']['App']['LoadFromJSON']();
}

export function SaveToJSON(arg1, arg2) {
  return window['go']['main']['App']['SaveToJSON'](arg1, arg2);
}

export function SaveUsersToJSONFile(arg1) {
  return window['go']['main']['App']['SaveUsersToJSONFile'](arg1);
}
