// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllPerson() {
  return window['go']['main']['App']['GetAllPerson']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LoadFromJSON(arg1) {
  return window['go']['main']['App']['LoadFromJSON'](arg1);
}

export function SaveToJSON(arg1, arg2) {
  return window['go']['main']['App']['SaveToJSON'](arg1, arg2);
}

export function SaveUserToJSONFile(arg1) {
  return window['go']['main']['App']['SaveUserToJSONFile'](arg1);
}
